name = "wemem-worker"
main = "src/index.ts"
compatibility_date = "2023-11-21"
workers_dev = true
minify = true
routes = [
  { pattern = "worker.wemem.ai", custom_domain = true }
]

[limits]
cpu_ms = 500

[observability]
enabled = true
head_sampling_rate = 1